### ISSUE TITLE
Ngrok Tunnel from Google Colab not working

### ISSUE THREAD

**Issue by claudineisbezerra** [ngrok/ngrok-python#103]
Hi everyone,
I'm just getting started with Google Colab and NGrok to test an application, and I'm using a basic Flask example.

I've initiated a tunnel using an auth token, and when I visit [https://dashboard.ngrok.com/tunnels/agents](https://dashboard.ngrok.com/tunnels/agents), I can see that the tunnel has started successfully. It looks like ngrok and pyngrok are doing what they're supposed to do.

It seems like there might be some issue with the origin of Colab being blocked and it's not possible to access the expose URL.
**Does anyone have a simple working example they could share with me?**

This is the content of the Cells created at Google Colab:
#CELL1
![Cell1](https://github.com/ngrok/ngrok-python/assets/30300239/234320dd-ff5b-4208-8ddb-a41b8614e047)

#CELL2
![Cell2](https://github.com/ngrok/ngrok-python/assets/30300239/51ab6f50-f6fe-4e61-8beb-681bb8568ae2)

**Comment by salilsub** [comment]
HI @claudineisbezerra pyngrok is not an officially supported integration with ngrok, there is an [official python SDK](https://github.com/ngrok/ngrok-python) which I would recommend using.

**Comment by CK-Ward** [comment]
Hi @claudineisbezerra , closing this out per Salil's recommendation to use our supported Python SDK —  please reach out if you have any questions with the SDK. Thank you!
