### ISSUE TITLE
Specify an `edge` for the connection

### ISSUE THREAD

**Issue by jimkring** [ngrok/ngrok-python#83]
In the parameters for `ngrok.forward()` (see [full configuration param's list](https://github.com/ngrok/ngrok-python#full-configuration)) I don't see any option to specify an `edge` or other `label` for the tunnel.

Is this possible from the python api?

**Comment by bobzilladev** [comment]
Hello, thanks for your question! There is a `labels` kwarg that can be used, here's an example:
`ngrok.forward("localhost:8080", proto="labeled", labels="edge:edghts_2G...", authtoken_from_env=True)`

We'll get the documentation updated to add it. Thanks again!

**Comment by jimkring** [comment]
That's great it's already supported by the API!

A couple other points:

1. I created [a suggestion](https://github.com/ngrok/ngrok-python/issues/85) to make this a named parameter.

2. It would probably make sense to add an option to the **ngrok dashboard** for creating a tunnel using the Python (Rust, Go, etc.) APIs, as described in the screenshot below:

![2024-01-04_12-45-55](https://github.com/ngrok/ngrok-python/assets/381432/ca711486-8a17-4289-8058-333f1d347344)

**Comment by jimkring** [comment]
@bobzilladev another thought:

3. The example you provided `labels="edge:edghts_2G..."` shows a truncated string.  What's the format for passing multiple labels? e.g. is it a comma-delimited list like `labels="key1:value1,key2:value2"`?

**Comment by bobzilladev** [comment]
Will try to answer these questions here:

1. For a more concrete style the builder pattern configuration can be used, here's an example of that which is more explicit: [ngrok-labeled.py](https://github.com/ngrok/ngrok-python/blob/main/examples/ngrok-labeled.py#L19)
1. Adding to the start a tunnel pane has been discussed, for now the python getting started page is a dashboard resource to help initial setup: [dashboard.ngrok.com/get-started/setup/python](https://dashboard.ngrok.com/get-started/setup/python)
1. The labels kwarg can take an array as well, `labels=["key1:value1", "key2:value2"]`

Hopefully that's useful, thanks for the feedback!

**Comment by jimkring** [comment]
Yes, thanks!
