### ISSUE TITLE
How to use ngrok python sdk to enable ngrok Agent API

### ISSUE THREAD

**Issue by banhao** [ngrok/ngrok-python#94]
Before I used pyngrok and ngrok Agent API 'http://127.0.0.1:4040/api/tunnels' was enabled by default. 
So when I switch to use `ngrok`, I don't know how to enable the ngrok Agent API 'http://127.0.0.1:4040/api/tunnels' by using `ngrok`

**Comment by Abdiramen** [comment]
Are you looking for a web interface for `ngrok-python`? If so, that doesn't exist in `ngrok-python` yet.

**Comment by banhao** [comment]
So will you add this feature in the future? Thanks!

**Comment by bobzilladev** [comment]
Hello! There is a Python library for interacting with the server-side API which can be used along side the SDK, which may provide the functionality you are looking for, that can be found here: https://github.com/ngrok/ngrok-api-python

**Comment by banhao** [comment]
I need Web Interface which is looks like this
![gnrok-inspect-tab](https://github.com/ngrok/ngrok-python/assets/13863700/6123abc0-d805-46ba-8517-c557543a155e)
Can check the request and response data, header, raw data, etc.

**Comment by bobzilladev** [comment]
Ah, for analyzing traffic there is a product update coming on the horizon, see the [Traffic Inspection](https://ngrok.com/docs/obs/traffic-inspection/) section of the docs for information around that.

**Comment by banhao** [comment]
> Ah, for analyzing traffic there is a product update coming on the horizon, see the [Traffic Inspection](https://ngrok.com/docs/obs/traffic-inspection/) section of the docs for information around that.

yes, but how to enable it by using python `import ngrok`? Seems it is not enable by default when using `listener = ngrok.forward(5000, authtoken_from_env=True)`

**Comment by bobzilladev** [comment]
Aye, the local web interface is only for the Agent. But going forward both the Agent and the SDK's will populate data in the cloud based traffic inspector in the ngrok dashboard.

**Comment by salilsub** [comment]
I'm going to mark this as a "not planned". We won't be making any direct changes to the python SDK, but the recommended solution is to use our traffic inspector on the ngrok dashboard.
